In [17]:
import pandas as pd

# 创建数据
data = {
    '产品类别': ['电子产品', '电子产品', '家用电器', '家用电器', '服装鞋帽',
              '服装鞋帽', '食品饮料', '食品饮料', '电子产品', '家用电器'],
    '产品名称': ['智能手机', '蓝牙耳机', '电饭煲', '吸尘器', '运动鞋',
              '羽绒服', '牛奶', '矿泉水', '平板电脑', '微波炉'],
    '销售数量': [12, 25, 8, 5, 20, 10, 30, 50, 6, 7],
    '单价': [2999, 199, 499, 1299, 399, 899, 65, 3, 4999, 799]
}

df = pd.DataFrame(data)

# 写入CSV文件
df.to_csv('data/sales.csv',
          index=False,           # 不保存行索引
          encoding='utf-8-sig',  # 编码格式（含BOM，Excel打开不乱码）
          float_format='%.2f')   # 浮点数保留2位小数

In [5]:
# 增加一行并写入
df2 = pd.read_csv('data/sales2.csv', usecols=['产品名称','销售数量','单价'])
df2['销售金额'] = df2['单价'] * df2['销售数量']
df2.to_csv('data/sales2.csv', index=False, encoding='utf-8-sig', float_format='%.2f')

In [8]:
df3 = pd.read_csv('data/sales2.csv', usecols=['产品名称','销售数量','单价'], index_col='产品名称')
# 选择行
df3.iloc[0:5:1]  # 不包括end
df3.loc['智能手机':'矿泉水':1]  # 包括end

      销售数量    单价
产品名称
智能手机    12  2999
蓝牙耳机    25   199
电饭煲      8   499
吸尘器      5  1299
运动鞋     20   399
羽绒服     10   899
牛奶      30    65
矿泉水     50     3

In [16]:
df4 = pd.read_csv('data/sales.csv')
df4[df4['销售数量'] >= 10]
df4[df4['产品类别'].isin(['电子产品','家用电器'])]
df4[df4['单价'].between(500,1000)]  # 包含左右边界
df4[(df4['销售数量'] >= 10) & (df4['单价'] >= 500)]

   产品类别  产品名称  销售数量    单价
0  电子产品  智能手机    12  2999
5  服装鞋帽   羽绒服    10   899