In [3]:
import pandas as pd

df = pd.read_csv('data/sales.csv')
df.sort_values('单价')
df.sort_values(['单价','销售数量'], ascending=[True, False])

   产品类别  产品名称  销售数量    单价
7  食品饮料   矿泉水    50     3
6  食品饮料    牛奶    30    65
1  电子产品  蓝牙耳机    25   199
4  服装鞋帽   运动鞋    20   399
2  家用电器   电饭煲     8   499
9  家用电器   微波炉     7   799
5  服装鞋帽   羽绒服    10   899
3  家用电器   吸尘器     5  1299
0  电子产品  智能手机    12  2999
8  电子产品  平板电脑     6  4999

In [12]:
df2 = pd.read_csv('data/sales.csv')
df2['销售金额'] = df['单价'] * df['销售数量']
# 根据产品类别分组，统计销售数量
df2.groupby('产品类别')['销售数量'].sum()
# 根据产品类别分组，统计订单数量
df2.groupby('产品类别')['销售数量'].count()

df2.groupby('产品类别')['单价'].min()
df2.groupby('产品类别').agg({'销售数量':'sum', '单价':'mean'})

      销售数量           单价
产品类别
家用电器    20   865.666667
服装鞋帽    30   649.000000
电子产品    43  2732.333333
食品饮料    80    34.000000